### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by FuckingToasters** [RevertIT/mybb-rt_livesearch#4]
So i installed the Plugin and then i got this error when triyng to visit the plugin list n the ACP:

Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/html/recreate_tables/inc/plugins/rt_livesearch/src/Core.php on line 27

**Comment by RevertIT** [comment]
This plugin has been developed for PHP >= 8.0.
