### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by Eldenroot** [RevertIT/mybb-rt_livesearch#5]
Please, could you add a compatibility with 7.4?

I am asking because MyBB itself is not fully compatible (yet) with PHP 8.0 and newer so I am forced to use oldder version... including some plugins...

Thank you!

I have a blank plugin page when I wanna use your plugin with lower PHP.

@RevertIT 

Thank you!

**Comment by RevertIT** [comment]
Duplicate of #4

Hi, I made the plugin with a focus on getting people to transition to PHP 8 and making it future-proof.

As the plugin is open source, anyone is free to fork it and downgrade it for their needs.

**Comment by Eldenroot** [comment]
I understand but MyBB 1.8.33 is not compatible...
